DATASTORE = "scripts/demo/datastore"
PDF_DIR ="scripts/demo/pdf_materials"
RESULT_DIR="scripts/demo/answer_log"
TOP_K = 3
CACHE_DIR = "../Localmodels"
DEBUG = True
MAX_TOKENS = 256
TEST_DIR = "scripts/demo/test"
BASE_DIR = "/home/bingxing2/home/scx7655/workspace/VisRAG"
QA_BATCH_SIZE = 150
QA_IMG_NUM = 3